disabled: false
reporter:
  logSpans: false
  localAgentHostPort: "jaeger-agent.social-network.svc.cluster.local:16686"
  queueSize: 1000000
  bufferFlushInterval: 10
sampler:
  type: "probabilistic"
  param: 0.1